### ISSUE TITLE
Upgrade @actions/core to fix deprecated syntax for setOutput

### ISSUE THREAD

**Issue by andyasberry** [Equip-Collaboration/diff-line-numbers#7]
@OmniSliver I see you've merged changes to this repo before. Hoping you can help out here!

I believe this action will stop working in June 2023, due to changes for the setoutput command. I think we only need to update the version of `@actions/core` to `^1.10.0` in package.json:

https://github.com/Equip-Collaboration/diff-line-numbers/blob/a433af7f87e67f0351148aea9a9e45a7e29fdc94/package.json#L27

Since I can't issue a pull request, here is a patch that may be helpful:

[setoutput.patch](https://github.com/Equip-Collaboration/diff-line-numbers/files/11491560/setoutput.patch)

**Comment by OmniSliver** [comment]
Solved in #8 and released in v1.1.1. Thanks for the patch!
